/* AUTO-GENERATED by tools/tokens-build/index.mjs — do not edit. */
/* Source: packages/@njz-os/ui/tokens/tokens.json */

export const color = {
  "bg": "#0F172A",
  "bgElevated": "#1E293B",
  "text": "#F8FAFC",
  "textMuted": "#94A3B8",
  "accentTeal": "#14B8A6",
  "accentWarm": "#F97316",
  "success": "#22C55E",
  "danger": "#EF4444",
  "moduleFocus": "#F97316",
  "moduleSound": "#A855F7",
  "moduleBlocker": "#EF4444",
  "moduleWrite": "#0EA5E9",
  "moduleLearn": "#EAB308",
  "moduleTrain": "#22C55E",
  "moduleWorld": "#14B8A6",
} as const;

export type ColorToken = typeof color;

export const space = {
  "0": "0",
  "1": "4px",
  "2": "8px",
  "3": "12px",
  "4": "16px",
  "6": "24px",
  "8": "32px",
  "12": "48px",
  "16": "64px",
} as const;

export type SpaceToken = typeof space;

export const radius = {
  "sharp": "2px",
  "small": "4px",
  "pixel": "0",
} as const;

export type RadiusToken = typeof radius;

export const typography = {
  "familyDisplay": "'Space Grotesk', system-ui, -apple-system, sans-serif",
  "familyBody": "Inter, system-ui, -apple-system, sans-serif",
  "familyMono": "ui-monospace, 'SF Mono', Menlo, monospace",
  "scaleXs": "0.75rem",
  "scaleSm": "0.875rem",
  "scaleBase": "1rem",
  "scaleLg": "1.125rem",
  "scaleXl": "1.25rem",
  "scale2xl": "1.5rem",
  "scale3xl": "1.875rem",
  "scale4xl": "2.25rem",
  "scale5xl": "3rem",
  "weightRegular": "400",
  "weightMedium": "500",
  "weightSemibold": "600",
  "weightBold": "700",
} as const;

export type TypographyToken = typeof typography;

export const motion = {
  "durationInstant": "0ms",
  "durationFast": "120ms",
  "durationBase": "240ms",
  "durationSlow": "480ms",
  "easeStandard": "cubic-bezier(0.4, 0, 0.2, 1)",
  "easeDecelerate": "cubic-bezier(0, 0, 0.2, 1)",
  "easeAccelerate": "cubic-bezier(0.4, 0, 1, 1)",
} as const;

export type MotionToken = typeof motion;
