#!/usr/bin/env bash
# .devcontainer/setup.sh
# Post-create setup for the SATOR / RadiantX Codespace.
# Installs kimi-cli and writes per-user config from injected secrets.
set -euo pipefail

echo "═══════════════════════════════════════════════"
echo "  SATOR Codespace — post-create setup"
echo "═══════════════════════════════════════════════"

# ── 1. Install Python project dependencies ──────────────────────────────────
echo "▶ Installing Python analytics dependencies…"
pip install --quiet --upgrade pip
pip install --quiet -r axiom-esports-data/extraction/requirements.txt

# ── 2. Install kimi-cli ──────────────────────────────────────────────────────
echo "▶ Installing kimi-cli…"
pip install --quiet "kimi-cli>=1.15.0"

# Confirm installation
KIMI_VERSION=$(kimi --version 2>/dev/null || echo "unknown")
echo "  kimi-cli version: ${KIMI_VERSION}"

# ── 3. Write ~/.kimi/config.toml ────────────────────────────────────────────
# The config.toml references the KIMI_API_KEY environment variable at runtime;
# it is not embedded here so the secret never touches the filesystem at rest.
echo "▶ Writing ~/.kimi/config.toml…"
mkdir -p "${HOME}/.kimi"

cat > "${HOME}/.kimi/config.toml" << 'TOML'
# Kimi Code CLI — user configuration
# Generated by .devcontainer/setup.sh
# Runtime override: set KIMI_API_KEY, KIMI_BASE_URL, or KIMI_MODEL_NAME env vars.

default_model = "kimi-for-coding"

[providers.kimi]
type     = "kimi"
base_url = "https://api.moonshot.cn/v1"
# api_key is read from the KIMI_API_KEY environment variable at runtime.
# Do NOT paste real keys here.
api_key  = "REPLACED_BY_ENV_VAR"

[models.kimi-for-coding]
provider         = "kimi"
model            = "kimi-k2-5"
max_context_size = 131072

[loop_control]
max_steps_per_turn     = 100
max_retries_per_step   = 3
max_ralph_iterations   = 0

[services]
TOML

echo "  ~/.kimi/config.toml written."

# ── 4. Write ~/.kimi/mcp.json (MCP server config) ───────────────────────────
# Enables the built-in GitHub MCP server for repository and PR tooling.
echo "▶ Writing ~/.kimi/mcp.json…"

cat > "${HOME}/.kimi/mcp.json" << 'JSON'
{
  "mcpServers": {
    "github": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-github"],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "${GITHUB_TOKEN}"
      }
    }
  }
}
JSON

echo "  ~/.kimi/mcp.json written."

# ── 5. Inject KIMI_API_KEY at runtime (replace placeholder in config) ────────
# kimi-cli reads KIMI_API_KEY from the environment automatically, so we only
# need to ensure the env var is available. The placeholder in config.toml is
# overridden by the env var — no sed required.
if [ -n "${KIMI_API_KEY:-}" ]; then
    echo "  ✅ KIMI_API_KEY secret detected — kimi-cli will use it automatically."
else
    echo "  ⚠️  KIMI_API_KEY is not set."
    echo "     Add it under: GitHub → Settings → Codespaces → Secrets"
    echo "     or run: export KIMI_API_KEY=<your-key>"
fi

# ── 6. Install Node dependencies (TypeScript packages) ──────────────────────
echo "▶ Installing Node.js workspace dependencies…"
npm install --silent

# ── 7. Final confirmation ────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════"
echo "  ✅ Setup complete"
echo ""
echo "  Quick start:"
echo "    kimi --help                  # full CLI reference"
echo "    kimi -p 'Hello Kimi'         # single-turn prompt"
echo "    kimi -y -p 'Review my code'  # auto-approve (yolo mode)"
echo "    kimi term                    # TUI terminal interface"
echo "    kimi web                     # browser-based interface"
echo ""
echo "  Config files:"
echo "    ~/.kimi/config.toml          # LLM provider + model config"
echo "    ~/.kimi/mcp.json             # MCP tool server config"
echo "    .kimi/config.toml            # project-local overrides (this repo)"
echo "═══════════════════════════════════════════════"
