#!/usr/bin/env node
/**
 * PRX-25-ENH-05 — Shared design-token compile step.
 *
 * Reads packages/@njz-os/ui/tokens/tokens.json and emits:
 *
 *   - packages/@njz-os/ui/src/tokens/generated.css   (CSS custom properties)
 *   - packages/@njz-os/ui/src/tokens/generated.ts    (typed TS exports)
 *
 * Naming convention:
 *   `<group>.<name>`  →  `--njz-<group>-<name>` (CSS)  →  `<groupCamel>.<nameCamel>` (TS)
 *
 * Idempotent: re-running with no source change produces identical output.
 *
 * Usage:
 *   node tools/tokens-build/index.mjs
 *   node tools/tokens-build/index.mjs --check        (CI mode; non-zero if drift)
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..', '..');
const TOKENS_JSON = join(
  REPO_ROOT,
  'packages',
  '@njz-os',
  'ui',
  'tokens',
  'tokens.json'
);
const OUT_CSS = join(
  REPO_ROOT,
  'packages',
  '@njz-os',
  'ui',
  'src',
  'tokens',
  'generated.css'
);
const OUT_TS = join(
  REPO_ROOT,
  'packages',
  '@njz-os',
  'ui',
  'src',
  'tokens',
  'generated.ts'
);

const argv = new Set(process.argv.slice(2));
const checkMode = argv.has('--check');

const tokens = JSON.parse(readFileSync(TOKENS_JSON, 'utf8'));

const SKIP_KEYS = new Set([
  '$schema',
  '_doc',
  '_framework',
  '_updated',
]);

function camel(s) {
  return s.replace(/-([a-z0-9])/g, (_m, c) => c.toUpperCase());
}

function buildCss() {
  const lines = [];
  lines.push('/* AUTO-GENERATED by tools/tokens-build/index.mjs — do not edit. */');
  lines.push('/* Source: packages/@njz-os/ui/tokens/tokens.json */');
  lines.push(':root {');
  for (const [group, members] of Object.entries(tokens)) {
    if (SKIP_KEYS.has(group)) continue;
    for (const [name, def] of Object.entries(members)) {
      const v = typeof def === 'object' && def !== null ? def.value : def;
      lines.push(`  --njz-${group}-${name}: ${v};`);
    }
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function buildTs() {
  const lines = [];
  lines.push('/* AUTO-GENERATED by tools/tokens-build/index.mjs — do not edit. */');
  lines.push('/* Source: packages/@njz-os/ui/tokens/tokens.json */');
  lines.push('');
  for (const [group, members] of Object.entries(tokens)) {
    if (SKIP_KEYS.has(group)) continue;
    const camelGroup = camel(group);
    lines.push(`export const ${camelGroup} = {`);
    for (const [name, def] of Object.entries(members)) {
      const v = typeof def === 'object' && def !== null ? def.value : def;
      const camelName = camel(name);
      const escaped = JSON.stringify(v);
      lines.push(`  ${JSON.stringify(camelName)}: ${escaped},`);
    }
    lines.push('} as const;');
    lines.push('');
    lines.push(`export type ${camelGroup.charAt(0).toUpperCase() + camelGroup.slice(1)}Token = typeof ${camelGroup};`);
    lines.push('');
  }
  return lines.join('\n');
}

const css = buildCss();
const ts = buildTs();

if (checkMode) {
  let drift = false;
  if (!existsSync(OUT_CSS) || readFileSync(OUT_CSS, 'utf8') !== css) {
    console.error('drift: generated.css differs from build output');
    drift = true;
  }
  if (!existsSync(OUT_TS) || readFileSync(OUT_TS, 'utf8') !== ts) {
    console.error('drift: generated.ts differs from build output');
    drift = true;
  }
  if (drift) {
    console.error(
      '\nRun `node tools/tokens-build/index.mjs` and commit the result.'
    );
    process.exit(1);
  }
  console.log('✓ generated token files in sync with tokens.json');
  process.exit(0);
}

writeFileSync(OUT_CSS, css);
writeFileSync(OUT_TS, ts);
console.log(`✓ wrote ${OUT_CSS}`);
console.log(`✓ wrote ${OUT_TS}`);
